pipeline {
    agent none

    stages {
        stage('build') {
            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Compile vote app'
                dir('vote'){
                    sh "pip install -r requirements.txt"
                }
            }
        }
        stage('test') {
            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Running Unit Tests on vote app'
                dir('vote'){
                    sh "pip install -r requirements.txt"
                    sh "nosetests -v"
                }
            }
        }
        stage('docker-package') {
            agent any
            when {
                branch 'master'
                changeset "**/vote/**"
            }
            steps {
                echo 'Packaging vote app with docker'
                script {
                    docker.withRegistry('https://docker.hyca.io/', 'nexus-login') {
                        def voteImage = docker.build("docker.hyca.io/vote:v${env.BUILD_ID}", "./vote")
                        voteImage.push()
                        voteImage.push("latest")
                    }
                }
            }
        }
    }
    post {
        always{
            echo 'Build pipeline for vote is complete..'
        }
    }
}